import type { Paper } from '@/types/paper';

const now = new Date().toISOString();

export const demoPapers: Paper[] = [
  {
    id: 'demo-1',
    title: 'Tool-Augmented Agents for Complex Scientific Workflows',
    authors: ['Lin', 'Wang', 'Zhao'],
    year: 2025,
    venue: 'NeurIPS',
    doi: '',
    arxiv_id: '2501.12345',
    abstract: 'A compact benchmark and framework for autonomous paper-analysis agents.',
    summary: '针对科研流程的 Agent 框架与评测基准。',
    category: 'Agent',
    tags: ['agent', 'workflow'],
    file_name: 'demo-agent.pdf',
    original_path: '',
    managed_path: '',
    thumbnail_path: '',
    is_favorite: false,
    read_status: 'unread',
    notes: '示例数据，仅用于界面展示。',
    file_hash: '',
    last_opened_at: '',
    last_read_page: 1,
    last_read_at: '',
    metadata_completed_at: '',
    is_metadata_incomplete: true,
    duplicate_key: '',
    duplicate_reason: '',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-2',
    title: 'Efficient Retrieval-Augmented Generation in Domain Corpora',
    authors: ['Chen', 'Liu'],
    year: 2024,
    venue: 'ACL',
    doi: '',
    arxiv_id: '',
    abstract: 'Study of latency-quality tradeoff in local RAG systems.',
    summary: '本地 RAG 系统的时延与质量平衡研究。',
    category: 'RAG',
    tags: ['rag', 'retrieval'],
    file_name: 'demo-rag.pdf',
    original_path: '',
    managed_path: '',
    thumbnail_path: '',
    is_favorite: true,
    read_status: 'reading',
    notes: '',
    file_hash: '',
    last_opened_at: '',
    last_read_page: 1,
    last_read_at: '',
    metadata_completed_at: '',
    is_metadata_incomplete: false,
    duplicate_key: '',
    duplicate_reason: '',
    created_at: now,
    updated_at: now,
  },
];
